# Please read the notes before editing this file :)

# Default worlds configurations
worlds:
  overworld: uhc
  nether: uhc_nether
  end: uhc_the_end
  arena: arena
  lobby: lobby
# Default toggleable configurations
toggle:
  advancements: false
  anti-item-destruction: true
  auto-ls: true
  auto-mining-warn: true
  bookshelves: true
  end: false
  explosives: true
  fire-aspect: false
  flame: true
  fletchers: true
  ghast-drop: true
  horses: true
  mobs: false
  nerfed-strength: true
  nether: false
  notch: true
  starter-books: true
  stats: true
  trades: true
  potions: # Three possible values: ON, OFF or TIER1
    poison: ON
    swiftness: ON
    fire-resistance: ON
    turtle-master: ON
    slowness: ON
    invisibility: ON
    regeneration: OFF
    strength: TIER1
    healing: OFF
    harming: ON
    water-breathing: ON
    weakness: ON
    leaping: ON
    slow-falling: ON
    infestation: ON
    wind-charging: ON
    oozing: ON
    weaving: ON
  customcrafts:
    totem: true
    mace: false
    breeze_rod: true
    trident: true
    elytra: false
    golden_head: true
    spectral_arrows: true
    glistering_melon: true
    tnt_minecart: true
    lectern: true
# Default border configurations
border:
  gui-default-list:
    overworld: [600, 1000, 1600, 2000, 3000, 4000]
    nether: [500, 1000, 1500, 2000]
  overworld: 2000
  meetup: 200
  timer: 5 # minutes
  tp-border: true
  speed: 2.0 # blocks per minute
  border-list:
    - 1000
    - 500
    - 200
  nether: 1500
  nether-meetup: 100
  nether-timer: 5 # minutes
  nether-tp-border: true
  nether-speed: 2.0 # blocks per minute
  nether-border-list:
    - 750
    - 375
    - 150
  # When a player is teleported from the Nether to the Overworld at Meetup start,
  # this value is subtracted from the border size to avoid scattering them too close
  # to the edge while it's moving. Only applies when tpborder is disabled.
  nether-scatter-inset: 100
# Default durations
duration: # in minutes
  pvp: 15
  meetup: 15
  final-heal: 0
# Default rates
rates:
  xp-kill: 3 # levels
  flint: 30 # %
  apple: 2 # %
  glass: 40 # %
# Default ???
settings:
  location-finder:
    max-y: 110
    search-attempts: 200
  start:
    prestart-countdown: 6
    invulnerability-delay-ticks: 300
  meetup:
    invulnerability-duration-ticks: 40
    fire-resistance-duration-ticks: 200
  timer:
    pvp-reminders: "3600,1800,900,600,300,60"
    meetup-reminders: "3600,1800,900,600,300,60"
  team:
    default-size: 2
    max-size: 5
    min-size: 1