name: polaris-uhc
version: ${project.version}
main: us.polarismc.polarisuhc.Main
api-version: '1.21'
authors: [putindeer, tmpst]
description: UHC Plugin for PolarisMC
website: https://github.com/polaris-mc

commands:
  debug:
    description: Command used for debug info
    permission: uhc.dev
  gui:
    description: Command used to debug GUIs that might not be integrated into other GUIs or commands.
    permission: uhc.dev
  hex:
    description: Ccommand used to test hex colors.
    permission: uhc.dev
  teamhex:
    description: Command used to test team hex colors.
    permission: uhc.dev
  testteams:
    description: Command used to test teams.
    permission: uhc.dev
  testscatter:
    description: Command used to test scattering.
    permission: uhc.dev
  nametag:
    description: Command used to test nametags
    permission: uhc.dev
  createworld:
    description: Used for creating overworld/nether/end worlds.
    permission: uhc.host
  togglescenario:
    description: Used for toggling scenarios.
    permission: uhc.host
  emojiteam:
    description: Change the emoji of other team.
    permission: uhc.host
  maketeams:
    description: Used for messaging players about creating teams.
    permission: uhc.host
  solo:
    description: Used for giving a team to a player or making a solo team for every player without a team.
    permission: uhc.host
  quickstart:
    description: Used to start the UHC automatically.
    permission: uhc.host
  manualstart:
    description: Used to start the UHC manually.
    permission: uhc.host
  toggle:
    description: Used to toggle UHC features.
    permission: uhc.host
  world:
    description: Used to teleport yourself to other worlds.
    permission: uhc.host
  bookstuff:
    description: Send the book-related items you have on your inventory to your teammates.
    aliases: bs
  colorteam:
    description: Change the color of your team.
  minedores:
    description: Send the ores you have mined to your teammates.
    aliases: pmminedores
  ores:
    description: Send the ores you have on your inventory to your teammates.
    aliases: pmores
  teamchat:
    description: Enables your teamchat, allowing you to send private messages to your teammates.
    aliases: [chat, c, tc]
  team:
    description: Used for all kind of team commands.
  teamlocation:
    description: Sends your location to your teammates.
    aliases: tl
  teaminventory:
    description: Access a shared inventory for your team.
    aliases: ti
  scen:
    description: Shows the active scenarios inventory
    usage: /<command>
  reloadscenarios:
    description: Reloads each scenario's config file.
    permission: uhc.host